### ISSUE TITLE
Release to Maven Central

### ISSUE THREAD

**Issue by An-Nadein** [jpmorganchase/java-lint-assert#14]
Deploy linter to maven central so that it can be used as a dependency in other maven/gradle projects.
It's ok to be able to deploy from a local env as a first step. The goal is to be able to deploy from Travis builds on the master branch.

**Comment by An-Nadein** [comment]
The Sonatype user account already exists. Ask me for Sonatype username and password
Our GroupId is com.github.jpmorganchase.*

**Comment by abhangal** [comment]
Uploaded linter project to maven central from local. 
Please check at https://repo1.maven.org/maven2/com/github/jpmorganchase/lint-assert/core/0.1.7/

**Comment by An-Nadein** [comment]
done.
